apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.15.40-172.16.15.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: base
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool
