- name: install & configure basic software
  hosts: all
  become: true

  vars:
    packages:
      - htop

  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    
    - name: reboot
      ansible.builtin.reboot:
    
    - name: disable zram swap
      ansible.builtin.dnf:
        name: zram-generator-defaults
        state: absent

    - name: disable swap in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+\s+.*)$'
        replace: '# \1'

    - name: install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
    
    - name: reboot
      ansible.builtin.reboot:

    - name: Set up Kubernetes
      ansible.builtin.import_role:
        name: kubernetes