---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: prereq
      become: true
    - role: install
      become: true

- name: Setup k3s servers
  hosts: master
  roles:
    - role: k3s_server
      become: true
    - role: k3s_server_post
      become: true
    - role: rook
      become: true

- name: Setup k3s nodes
  hosts: node
  roles:
    - role: k3s_node
      become: true

