---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rook-block-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: ceph-block