---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rook-block-pvc-ec
spec:
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html   # This is where Nginx serves files from
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: test-rook-block-pvc-ec