---
# Name of the master group
group_name_master: master

# yamllint disable rule:line-length
agent_init_args: >-
  --server https://{{ apiserver_endpoint | ansible.utils.ipwrap }}:6443
  --token {{ hostvars[groups[group_name_master | default('master')][0]]['token'] | default(k3s_token) }}
  {{ extra_agent_args | default('') }}
