- name: Creating namespace
  ansible.builtin.shell: kubectl create namespace longhorn-system
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Installing open-iscsi 
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/deploy/prerequisite/longhorn-iscsi-installation.yaml -n longhorn-system
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Deploy longhorn helm chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
    force: true
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']