- name: Add coredns helm chart repo
  kubernetes.core.helm_repository:
    name: coredns
    repo_url: "https://coredns.github.io/helm"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Deploy coredns helm chart
  kubernetes.core.helm:
    name: coredns
    chart_ref: coredns/coredns
    release_namespace: kube-system
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
    force: true
    values:
      replicaCount: 3
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
