- name: Add rook chart repo
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: "https://charts.rook.io/release"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Deploy rook helm chart
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    kubeconfig: "{{ ansible_user_dir }}/.kube/config"
    force: true
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']