prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-ec-block
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    scrapeInterval: "5s"